name: Build Android APK
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # إجبار السيرفر على استخدام إصدار حديث جداً لحل مشكلة الدالة المفقودة
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install dependencies
        run: |
          npm install

      # توليد ملفات الأندرويد المفقودة تلقائياً سحابياً
      - name: Prebuild Expo Project
        run: |
          npx expo prebuild --platform android --no-install

      # بدء البناء والتجميع الفعلي لملف الـ APK
      - name: Build Android APK via Gradle
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      # استخراج ملف الـ APK وتقديمه لك كرابط تحميل مباشر
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nexa-counter-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
